rvm:
  - 2.4.4
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache:
  directories:
    - node_modules
    - vendor/bundle
before_install:
  - sudo apt-get install -y libxmlsec1 libxmlsec1-dev imagemagick
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem uninstall bundler -x || gem uninstall bundler -a || true
  - gem update --system 2.6.12
  - gem uninstall bundler -x -i /home/travis/.rvm/gems/ruby-2.4.1@global || gem uninstall bundler -a -i /home/travis/.rvm/gems/ruby-2.4.1@global || true
  - gem install bundler --version=1.15.1
  - nvm install v6.9
  - yarn install
  - cd $TRAVIS_BUILD_DIR/vendor/canvas_shim
  - yarn install
  - cd $TRAVIS_BUILD_DIR
  - npm install -g coffee-script@1.6.2
  - npm install -g gulp
  - npm install -g webpack
  - "export DISPLAY=:99.0"
  # Allow headful tests, see https://github.com/Googlechrome/puppeteer/issues/290
  # Enable user namespace cloning
  - "sudo sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB - for non headless test runs
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # grab Chromedriver for selenium
  - wget http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - mkdir -p /home/travis/bin
  - unzip chromedriver_linux64.zip -d /home/travis/bin/
install:
  - bundle install --path vendor/bundle --without production --jobs=3 --retry=1
before_script:
  - psql -c 'create database canvas_test;' -U postgres;
  - psql -U postgres -q -d $DB_NAME -f db/structure.sql # faster than db:test:prepare
  - bundle exec rake canvas:compile_assets_dev # skip build of styleguide, api docs, npm install
  - rm Gemfile.lock
  - STRONGMIND_SPEC=1 bundle install --path vendor/bundle --without production --jobs=3 --retry=1
  # - STRONGMIND_SPEC=1 RAILS_ENV=test bundle exec rake db:test:prepare
script:
  - STRONGMIND_SPEC=1 HEADLESS=1 bundle exec rspec spec_strongmind
