# it is intended that this be used exclusive of all other docker-compose.*yml files in CI
services:
  canvas:
    volumes:
      - "${PWD}/${LOCAL_WORKDIR}/.git:${DOCKER_WORKDIR}/.git"
    init: true
