# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2'
services:
  jobs: &BASE
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - api_docs:/usr/src/app/public/doc/api
      - brandable_css_brands:/usr/src/app/app/stylesheets/brandable_css_brands
      - bundler:/home/docker/.bundler/
      - canvas-docker-gems:/home/docker/.gem/
      - canvas-planner_node_modules:/usr/src/app/packages/canvas-planner/node_modules
      - canvas-planner_lib:/usr/src/app/packages/canvas-planner/lib
      - generated_1:/usr/src/app/public/javascripts/client_apps
      - generated_2:/usr/src/app/public/dist
      - generated_3:/usr/src/app/public/javascripts/compiled
      - i18nliner_node_modules:/usr/src/app/gems/canvas_i18nliner/node_modules
      - locales:/usr/src/app/config/locales/generated
      - log:/usr/src/app/log
      - node_modules:/usr/src/app/node_modules
      - pacts:/usr/src/app/pacts
      - quizzes_dist:/usr/src/app/client_apps/canvas_quizzes/dist
      - quizzes_node_modules:/usr/src/app/client_apps/canvas_quizzes/node_modules
      - quizzes_tmp:/usr/src/app/client_apps/canvas_quizzes/tmp
      - reports:/usr/src/app/reports
      - selinimum_node_modules:/usr/src/app/gems/selinimum/node_modules
      - styleguide:/usr/src/app/app/views/info
      - tmp:/usr/src/app/tmp
      - translations:/usr/src/app/public/javascripts/translations
      - yardoc:/usr/src/app/.yardoc
      - yarn-cache:/home/docker/.cache/yarn
    environment: &BASE-ENV
      RAILS_ENV: development
      ENCRYPTION_KEY: facdd3a131ddd8988b14f6e4e01039c93cfa0160

  webpack:
    <<: *BASE
    command: yarn run webpack

  web:
    <<: *BASE
    environment:
      <<: *BASE-ENV
      VIRTUAL_HOST: .canvas.docker

  postgres:
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  api_docs: {}
  brandable_css_brands: {}
  bundler: {}
  canvas-docker-gems: {}
  canvas-planner_node_modules: {}
  canvas-planner_lib: {}
  generated_1: {}
  generated_2: {}
  generated_3: {}
  i18nliner_node_modules: {}
  locales: {}
  log: {}
  node_modules: {}
  pg_data: {}
  pacts: {}
  quizzes_dist: {}
  quizzes_node_modules: {}
  quizzes_tmp: {}
  reports: {}
  selinimum_node_modules: {}
  styleguide: {}
  tmp: {}
  translations: {}
  yardoc: {}
  yarn-cache: {}
