name: rich-content-experience
owned_globs:
  - app/controllers/immersive_reader_controller.rb
  - app/views/courses/link_validator.html.erb
  - lib/course_link_validator.rb
  - packages/canvas-media/**/*
  - packages/canvas-rce/**/*
  - ui/features/accessibility/**/*
  - ui/features/course_link_validator/**/*
  - ui/features/files/**/*
  - ui/features/files_v2/**/*
  - ui/shared/block-content-editor/**/*
  - ui/shared/immersive-reader/**/*
