# to use this add docker-compose/lti-test-tool.override.yml
# to your COMPOSE_FILE var in .env

version: '2'
services:
  web:
    links:
      - lti-test-tool
  lti-test-tool:
    image: instructure/lti_tool_provider_example:latest
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: lti.docker
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@postgres:5432
