# to use this add docker-compose/consul.override.yml
# to your COMPOSE_FILE var in .env

version: '2'
services:
  web:
    links:
      - vault

  vault:
    build: ./docker-compose/vault
    command: server -dev
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "canvas_root_token"
      VIRTUAL_PORT: 8200
