development:
  base_url: http://canvasweb
  change_password_path: /users/edit
  nonexistent_user_path: /users/not_on_lms
  bitly_access_token: 12345689assdfe
  help_url: http://helpweb

test:
  base_url: https://test.bebraven.org/
  change_password_path: /users/edit
  nonexistent_user_path: /users/not_on_lms
  bitly_access_token: 12345689assdfe

staging:
  base_url: https://stagingjoin.bebraven.org/
  change_password_path: /users/edit
  nonexistent_user_path: /users/not_on_lms
  bitly_access_token: 12345689assdfe

production:
  google_analytics_account: UA-XXXXXXXX-1
  base_url: https://join.bebraven.org/
  change_password_path: /users/edit
  nonexistent_user_path: /users/not_on_lms
  bitly_access_token: 12345689assdfe
  help_url: https://help.bebraven.org

