common: &common
  adapter: postgresql
  host: postgres
  encoding: utf8
  username: postgres
  timeout: 5000
  prepared_statements: false
  use_qualified_names: true
  shard_name: public
  schema_search_path: "''"

production: &production
  <<: *common
  database: canvas
  open: true

development:
  <<: *production

test:
  <<: *common
  database: canvas_test_rails3_<%= ENV['TEST_ENV_NUMBER'] %>
  shard1: canvas_test_rails3_shard1
  shard2: canvas_test_rails3_shard2
  test_shard_1: canvas_test_rails3_shard1
  test_shard_2: canvas_test_rails3_shard2
