paths:
  public_dir: public
  sass_dir: app/stylesheets
  all_sass_bundles: '{.,gems/plugins/*}/app/stylesheets/**/[^_]*.s[ac]ss'
  brandable_variables_json: app/stylesheets/brandable_variables.json
  bundles_with_deps: public/dist/brandable_css/brandable_css_bundles_with_deps.json
  file_checksums: public/dist/brandable_css/brandable_css_file_checksums.json
  output_dir: public/dist/brandable_css
  browsers_yml: config/browsers.yml

indices:
  handlebars:
    path: public/dist/brandable_css/brandable_css_handlebars_index.json
    bundles: 'jst/**'
    keysz: 2

manifest_key_seperator: $$$$$$$$$$$

variants:
  new_styles_normal_contrast: {}
  new_styles_high_contrast: {}
  new_styles_normal_contrast_rtl: {}
  new_styles_high_contrast_rtl: {}
