development:
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  encoding: utf8
  username: <%= ENV['DB_USER'] %>
  database: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASS'] %>
  timeout: 5000
  prepared_statements: false
  pool: <%= ENV["DB_POOL"] || 5 %>
  use_qualified_names: true
  schema_search_path: "sisyphus,public"
  
production:
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  encoding: utf8
  username: <%= ENV['DB_USER'] %>
  database: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASS'] %>
  timeout: 5000
  prepared_statements: false
  pool: <%= ENV["DB_POOL"] || 5 %>
  use_qualified_names: true
  schema_search_path: "sisyphus,public"
  
sisyphus:
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  encoding: utf8
  username: <%= ENV['DB_USER'] %>
  database: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASS'] %>
  timeout: 5000
  prepared_statements: false
  pool: <%= ENV["DB_POOL"] || 5 %>
  use_qualified_names: true
  schema_search_path: "sisyphus,public"