Datafixup/EagerLoad:
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"
    - "**/lib/data_fixup/*.rb"

Lint/FreezeConstants:
  Enabled: true

Lint/NoFileUtilsRmRf:
  Enabled: true

Lint/NoSleep:
  Enabled: true
  Exclude:
    - "**/spec/selenium/test_setup/**/*.rb"

Migration/ConcurrentIndex:
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"

Migration/ModelBehavior:
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"
    - "lib/data_fixup/*.rb"
  Whitelist:
    - Canvas
    - DataFixup
    - Switchman
    - Shard
    - Account.default
    - Account.site_admin
    - "*.quoted_table_name"
    - "*.connection"
    - "*.transaction"
    - "*.find_ids_in_batches"
    - "*.find_ids_in_ranges"
    - "*.update_all"
    - "*.delete_all"
    - "ActiveRecord::Migration"

Migration/PrimaryKey:
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"

Migration/RemoveColumn:
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"

Migration/SendLater:
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"

Rails/SmartTimeZone:
  Enabled: true

Specs/EnsureSpecExtension:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/NoBeforeAll:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/NoBeforeOnceStubs:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/NoExecuteScript:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"
  Exclude:
    - "**/spec/selenium/test_setup/**/*.rb"

Specs/NoNoSuchElementError:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/NoStrftime:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/PreferFOverFj:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/ScopeHelperModules:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/DeterministicDescribedClasses:
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"
