---
ai_experiences:
  state: hidden
  applies_to: Course
  shadow: true
  display_name: AI Experiences
  description: Introduces AI Experiences - a new Canvas Learning Object.
  touch_context: true
  environments:
    ci:
      state: allowed_on
    development:
      state: allowed_on
ai_experiences_student_view:
  state: hidden
  applies_to: Course
  shadow: true
  display_name: AI Experiences Student View
  description: Enables the student view for AI Experiences.
  touch_context: true
ai_experiences_context_file_upload:
  state: hidden
  applies_to: Course
  shadow: true
  display_name: AI Experience Context File Upload
  description: Enables context file upload for AI Experiences. Requires AI Experiences feature flag to be enabled.
  touch_context: true
  environments:
    ci:
      state: allowed_on
    development:
      state: allowed_on
