---
skip_blueprint_module_downstream_changes:
  state: hidden
  applies_to: SiteAdmin
  display_name: Skip blueprint module downstream changes on deletion
  description: When enabled, prevents marking downstream changes on modules when syncing blueprint course deletions
skip_reactivating_deleted_attachments:
  state: hidden
  applies_to: RootAccount
  display_name: Skip reactivating deleted attachments on import
  description: When enabled, importing course content attachments will not reactivate previously deleted ones
selective_content_tag_export:
  state: hidden
  applies_to: SiteAdmin
  display_name: Selective Content Tag Export
  description: When enabled, allows selective export of content tags within a module during content shares. Only shared module items are exported, not the entire module.
