product_tours:
  type: setting
  state: hidden
  applies_to: RootAccount
  display_name: "Product Tours"
  description: "In-product training walkthrough and tourpoints for admins, teachers, and students"
responsive_awareness:
  state: hidden
  applies_to: RootAccount
  display_name: "Responsive Awareness"
  description: "Collection of responsive improvements throughout Canvas"
responsive_misc:
  state: hidden
  applies_to: RootAccount
  display_name: "Responsive Misc"
  description: "Collection of responsive improvements throughout Canvas"
files_dnd:
  state: hidden
  applies_to: RootAccount
  display_name: "Files Drag and Drop Enhancements"
  description: "Improve discoverability of drag and drop in Files"
conference_selection_lti_placement:
  state: hidden
  applies_to: SiteAdmin
  display_name: "Allow Conference Selection LTI placement"
  description: "Allows users to add LTI tools with conference_selection placement type"
