---
assignments_2_student:
  state: hidden
  display_name: Assignment Enhancements - Student
  description: Use the new assignments student page
  applies_to: Course
  root_opt_in: true
  beta: true

account_pronouns:
  state: hidden
  display_name: Pronouns for users
  description: Allows users to pick pronouns that will be displayed after their name when it is shown in the user interface.
  applies_to: RootAccount
  root_opt_in: true

notification_for_global_announcement:
  state: hidden
  display_name: Immediate notifications for global announcements
  description: If you turn this on, when an account admin goes to the page to create a global announcement, a checkbox will appear to send notification directly to users when announcement starts.
  applies_to: RootAccount
  root_opt_in: true
