---
caps_site_admin_test_feature:
  state: allowed
  applies_to: SiteAdmin
  display_name: This is a SiteAdmin test Feature Flag
  description: |-
    This flag will not cause any change in behavior.
assignments_2_teacher:
  state: hidden
  display_name: Assignments 2 Teacher View
  description: Use the new assignments teacher page
  applies_to: Course
  root_opt_in: true
  beta: false
  environments:
    production:
      state: disabled
bookmarking_for_enrollments_index:
  state: allowed
  applies_to: RootAccount
  display_name: Bookmarking for Enrollments Index API
  description: Use bookmarking for API pagination in Enrollments Index
discussion_topic_performance_enhancement:
  state: allowed
  applies_to: SiteAdmin
  display_name: Discussion Topic performance improvements for Bibsys
  description: Discussion Topics will not query permissions for every sub-discussion
  environments:
    ci:
      state: 'on'
