---
caps_site_admin_test_feature:
  state: allowed
  applies_to: SiteAdmin
  display_name: This is a SiteAdmin test Feature Flag
  description: |-
    This flag will not cause any change in behavior.
assignments_2_student:
  state: hidden
  display_name: Assignment Enhancements - Student
  description: Use the new assignments student page
  applies_to: Course
  root_opt_in: true
  beta: true
assignments_2_teacher:
  state: hidden
  display_name: Assignments 2 Teacher View
  description: Use the new assignments teacher page
  applies_to: Course
  root_opt_in: true
  beta: false
  environments:
    production:
      state: disabled
assignment_attempts:
  state: hidden
  applies_to: SiteAdmin
  display_name: Assignment Allowed Attempts
  description: Allow a teacher to set the number of allowed attempts on an assignment via the UI
assignment_bulk_edit:
  state: hidden
  applies_to: SiteAdmin
  display_name: Assignment Bulk Editing
  description: Allow teachers to change the dates on a set of assignments in one step
bookmarking_for_enrollments_index:
  state: allowed
  applies_to: RootAccount
  display_name: Bookmarking for Enrollments Index API
  description: Use bookmarking for API pagination in Enrollments Index
syllabus_course_summary_option:
  state: allowed
  applies_to: SiteAdmin
  display_name: Syllabus Course Summary Option
  description: Make the Course Summary (list of assignments and events) optional in the syllabus
la_620_old_rce_init_fix:
  state: hidden
  display_name: RCE Initialization Fix
  description: |-
    Under some conditions, the legacy RCE fails to initialize because tinymce hasn't added the
    editor instance to its internal list when the RCE requires it.
  applies_to: SiteAdmin
  root_opt_in: true
