---
new_equation_editor:
  state: hidden
  display_name: RCE's new and improved equation editor dialog
  description: Includes the equation editor in the @instructure/canvas-rce package
  applies_to: SiteAdmin
buttons_and_icons_root_account:
  state: allowed
  applies_to: RootAccount
  display_name: RCE Icon Maker
  description: |-
    Manage a library of custom icons from the RCE.
  environments:
    production:
      state: hidden
buttons_and_icons_cropper:
  state: hidden
  display_name: Cropper & Associated Features in Buttons & Icons
  description: |-
    When enabled, turns on the Button & Icons image cropper, course images
    source, and upload image source.
  applies_to: SiteAdmin
