---
assignments_2_student:
  state: hidden
  display_name: Assignment Enhancements - Student
  description: Use the new assignments student page
  applies_to: Course
  root_opt_in: true
assignments_2_teacher:
  state: hidden
  display_name: Assignments 2 Teacher View
  description: Use the new assignments teacher page
  applies_to: Course
  root_opt_in: true
  beta: false
  environments:
    production:
      state: disabled
bookmarking_for_enrollments_index:
  state: allowed
  applies_to: RootAccount
  display_name: Bookmarking for Enrollments Index API
  description: Use bookmarking for API pagination in Enrollments Index
submission_type_tool_placement:
  state: hidden
  applies_to: RootAccount
  display_name: Submission Type LTI Placement
  description: |-
    If an LTI tool configured with the placement is installed, will show a new entry in the
    assignment submission type dropdown to quickly configure the assignment for the tool
enable_fullstory:
  state: hidden
  display_name: Enable fullstory
  description: |-
    Include FullStory recording of the user's session
  applies_to: SiteAdmin
new_math_equation_handling:
  state: hidden
  display_name: "Math: Updated equation handling"
  description: |-
    Replaces the existing image of the math equation plus its hidden mathml
    with a MathJax processed version. This change provides better accessibility
    and many options for the reader to interact with the equation on the page.
  applies_to: RootAccount
autocreate_attachment_from_media_object:
  state: hidden
  display_name: Create Files After RCE Media Upload/Recording
  description: |-
    Creates file objects (initially hidden to students if in a Course) after
    media is uploaded or recorded through the RCE.
  applies_to: RootAccount
enhanced_grade_change_query:
  state: hidden
  display_name: Enhanced grade change auditing
  description: Allow searching grade change audit logs by multiple criteria
  applies_to: SiteAdmin
new_file_url_rewriting:
  state: hidden
  display_name: Update file links to prefer preview, not download
  description: |-
    Canvas rewrites file URLs in user generated content. In the process, it
    often added "/download" where it was not wanted and inappropriate. This
    setting updates how URL rewriting takes place to facilitate previewing
    files within Canvas and not downloading.
  applies_to: SiteAdmin
  environments:
    development:
      state: on
    ci:
      state: on
inline_math_everywhere:
  state: hidden
  display_name: "Math: Support LaTex math equations almost everywhere"
  description: |-
    With this feature, LaTex math equations entered into most
    text entry fields in Canvas will be processed by MathJax.
    LaTex delimited by \(...\) become inline equations, while
    $$...$$ will be rendered as a block.  For example,
    you could choose to title an Assignment \(\sqrt{x}\), or
    enter $$ax^2 + by + c = 0$$ in a submission comment.
    This feature requires that the "Math: Updated equation handling"
    flag is also on.
  applies_to: RootAccount
canvas_for_elementary:
  state: hidden
  display_name: Canvas for Elementary
  applies_to: RootAccount
  beta: true
  description: |-
    A simplified Canvas interface for K-5. Enable applicable
    subaccount(s) as K-5 accounts in account settings.
