---
translation:
  state: hidden
  applies_to: Course
  display_name: Course AI Translation
  description: AI translation controls for courses, currently limited to discussions and announcements.
translate_inbox_messages:
  state: hidden
  applies_to: RootAccount
  display_name: Inbox AI Translation
  description: Enable translation software when composing messages. Translate inbound messages automatically into user's preferred language.
