# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2.3'
services:
  jobs: &BASE
    build:
      context: .
    volumes:
      - code:/usr/src/app
      - bundle:/home/docker/.bundle/
      - canvas-docker-gems:/home/docker/.gem/
      - yarn-cache:/home/docker/.cache/yarn
    environment: &BASE-ENV
      ENCRYPTION_KEY: facdd3a131ddd8988b14f6e4e01039c93cfa0160
      RAILS_ENV: development

  webpack:
    <<: *BASE
    command: yarn run webpack

  web:
    <<: *BASE
    environment:
      <<: *BASE-ENV
      VIRTUAL_HOST: .canvas.docker
      VIRTUAL_PORT: 80
      HTTPS_METHOD: noredirect

  postgres:
    volumes:
      - pg_data:/var/lib/postgresql/data

  githook_installer:
    build:
      context: .
      dockerfile: 'Dockerfile.githook'
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
      - ./script:/tmp/script

volumes:
  code: {}
  bundle: {}
  canvas-docker-gems: {}
  pg_data: {}
  yarn-cache: {}



x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      mode: "two-way-resolved"
      alpha: "."
      beta: "volume://code"
      configurationBeta:
        permissions:
          defaultOwner: "id:9999"
          defaultGroup: "id:9999"
      ignore:
        paths:
          - "/.bundle/"
          - "/.byebug_history"
          - "/.ruby-version"
          - "!/packages/*/node_modules/"
          - "!/packages/*/es/"
          - "!/packages/*/lib/"
          - "/packages/*/node_modules/*"
          - "/packages/*/es/*"
          - "!/packages/canvas-rce/es/*"
          - "!/packages/babel-plugin-themeable-styles/lib/*"
          - "/packages/*/lib/*"
          - "!/packages/translations/lib/*"
          - "!/gems/**/node_modules/"
          - "/gems/**/node_modules/*"
          - "/packages/canvas-planner/.babel-cache"
          - "!/public/doc/api/"
          - "/public/doc/api/*"
          - "!/app/stylesheets/brandable_css_brands/"
          - "/app/stylesheets/brandable_css_brands/*"
          - "/packages/canvas-rce/canvas"
          - "!/public/dist/"
          - "/public/dist/*"
          - "!/config/locales/generated/"
          - "/config/locales/generated/*"
          - "!/log/"
          - "/log/*"
          - "!/node_modules/"
          - "/node_modules/*"
          - "!/pacts/"
          - "/pacts/*"
          - "!/reports/"
          - "/reports/*"
          - "!/app/views/info/"
          - "/app/views/info/*"
          - "!/tmp/"
          - "/tmp/*"
          - "!/public/javascripts/translations/"
          - "/public/javascripts/translations/*"
          - "!/.yardoc/"
          - "/.yardoc/*"
          - "/.vscode"
          - "/tags"
          - "/tags.*"
          - "/vendor/bundle/"
