# to use this add inst-cli/docker-compose/selenium.override.yml
# to your COMPOSE_FILE var in .env
# http://127.0.0.1:7900/?autoconnect=1&resize=scale&password=secret
# use this ^^ to peek into the test
services:
## We list all of the different standalone containers as `selenium-hub` since Jenkins
##  will use the actual hub + node configuration instead of a standalone for performance
##  reasons. Listing all of them as selenium-hub saves a great deal of configuration issues
## Chrome
  selenium-hub:
    image: selenium/standalone-chromium:137.0.7151.68
    shm_size: 2gb
    depends_on:
      - web
    labels:
        - "traefik.enable=true"
    init: true
    ports:
      - 4444:4444
      - 7900:7900
## Firefox
  # selenium-hub:
  #   image: selenium/standalone-firefox
  #   depends_on:
  #     - web
  #   init: true
  #   ports:
  #     - 4444:4444
  #     - 7900:7900
## Edge
  # selenium-hub:
  #   image: selenium/standalone-edge
  #   depends_on:
  #     - web
  #   init: true
  #   ports:
  #    - 4444:4444
  #    - 7900:7900
networks:
  default:
    external: true
    name: "inst_shared"